language: php

php:
  - "7.1"
  - "7.3"

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.3.*

services:
    - memcached
    - redis-server
    
before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/config:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/dependency-injection:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/http-kernel:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/stopwatch:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --no-scripts --no-interaction
  - composer dump-autoload -o
  - phpenv config-add ./Tests/travis.ini

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
