language: php

php:
  - "5.6"
#  - "7.0" Services are not availlable in Travis for the moment

services:
    - memcache
    - memcached
    - redis-server
    
before_script:
  - composer self-update
  - composer install --no-scripts --no-interaction
  - composer dump-autoload -o
  - phpenv config-add ./Tests/travis.ini

after_script:
    - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
